mb_task_index:
    path: /index
    defaults: { _controller: MBUserBundle:Task:index }
    
mb_task_create:
    path: /create
    defaults: { _controller: MBUserBundle:Task:create }
    methods: POST
    
mb_task_add:
    path: /add
    defaults: { _controller: MBUserBundle:Task:add }
    
mb_task_update:
    path: /update/{id}
    defaults: { _controller: MBUserBundle:Task:update }
    methods: [POST, PUT]
    
mb_task_edit:
    path: /edit/{id}
    defaults: { _controller: MBUserBundle:Task:edit }
    
mb_task_view:
    path: /view/{id}
    defaults: { _controller: MBUserBundle:Task:view }
    
mb_task_delete:
    path: /delete/{id}
    defaults: { _controller: MBUserBundle:Task:delete }
    methods: [POST, DELETE]
    
mb_task_redirect_add:
    path: /create
    defaults:
        _controller: MBUserBundle:Task:add
        path: /add
        permanent: true
        
mb_task_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: MBUserBundle:Task:edit
        path: /edit/{id}
        permanent: true