mb_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MBUserBundle:Default:index }
    
mb_user_index:
    path: /user/index
    defaults: { _controller: MBUserBundle:User:index }
    
mb_user_add:
    path: /user/add
    defaults: { _controller: MBUserBundle:User:add }
    
mb_user_edit:
    path: /user/edit/{id}
    defaults: { _controller: MBUserBundle:User:edit }
    
mb_user_view:
    path: /user/view/{id}
    defaults: { _controller: MBUserBundle:User:view }
    
mb_user_delete:
    path: /user/delete/{id}
    defaults: { _controller: MBUserBundle:User:delete }

